name: release

on:
  push:
    tags:
      - v*

jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - run: echo "PATCH=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - run: echo "MINOR=${PATCH%.*}" >> $GITHUB_ENV
      - run: echo "MAJOR=${MINOR%.*}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            sourcegraph/scip-rust:latest
            sourcegraph/scip-rust:${{ env.PATCH }}
            sourcegraph/scip-rust:${{ env.MINOR }}
            sourcegraph/scip-rust:${{ env.MAJOR }}
